lib/find_my_personal_web/router.ex
defmodule FindMyPersonalWeb.Router do
  use FindMyPersonalWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  # coveralls-ignore-start
  pipeline :api do
    plug :accepts, ["json"]
  end

  # coveralls-ignore-stop

  scope "/", FindMyPersonalWeb do
    pipe_through :browser

    resources "/teacher", TeacherController
    resources "/members", MemberController

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  scope "/api", FindMyPersonalWeb.Api, as: :api do
    pipe_through :api

    resources "/members", MemberController
    resources "/teacher", TeacherController, except: [:new, :edit]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  # coveralls-ignore-start
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: FindMyPersonalWeb.Telemetry
    end
  end

  # coveralls-ignore-stop
end

lib/find_my_personal_web/templates/page/index.html.eex
<section>
  <article>
    <h2>Teachers</h2>
    <ul>
      <%= for teacher <- @teachers do %>
        <li key="<%= teacher.id %>">
          <%= link teacher.name, to: Routes.teacher_path(@conn, :show, teacher) %>
        </li>
      <% end %>
    </ul>
  </article>
  <article>
    <h2>Members</h2>
    <ul>
      <%= for member <- @members do %>
        <li key="<%= member.id %>">
          <%= link member.name, to: Routes.member_path(@conn, :show, member) %>
        </li>
      <% end %>
    </ul>
  </article>
</section>